package com.example.airefactoring.mcp

import com.example.airefactoring.refactoring.makestatic.JavaMakeStaticMemberKind
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

@Serializable
enum class McpRefactoringErrorCode {
    FILE_NOT_FOUND,
    OUTSIDE_PROJECT,
    NOT_JAVA_FILE,
    READ_ONLY,
    INVALID_RANGE,
    INVALID_METHOD_NAME,
    INVALID_VARIABLE_NAME,
    INVALID_FIELD_NAME,
    NO_TARGET_METHOD,
    UNSUPPORTED_METHOD,
    INVALID_PARAMETER_NAME,
    INVALID_PARAMETER_TYPE,
    INVALID_PARAMETER_POSITION,
    INVALID_DEFAULT_VALUE,
    UNSUPPORTED_USAGE,
    REFACTORING_CONFLICT,
    NO_TARGET_VARIABLE,
    UNSUPPORTED_VARIABLE,
    NO_EXTRACTABLE_ELEMENTS,
    NO_INTRODUCIBLE_EXPRESSION,
    UNSUPPORTED_EXPRESSION,
    UNSUPPORTED_DESTINATION,
    PREPARE_FAILED,
    REFACTORING_FAILED,
    UNSUPPORTED_TARGET,
    INVALID_VISIBILITY,
}

@Serializable
@ConsistentCopyVisibility
data class McpRefactoringResult private constructor(
    val ok: Boolean,
    val operation: String? = null,
    val filePath: String? = null,
    val projectBasePath: String? = null,
    val methodName: String? = null,
    val requestedVariableName: String? = null,
    val actualVariableName: String? = null,
    val variableType: String? = null,
    val requestedFieldName: String? = null,
    val actualFieldName: String? = null,
    val fieldType: String? = null,
    val fieldModifiers: List<String>? = null,
    val targetClassQualifiedName: String? = null,
    val initializationPlace: String? = null,
    val variableName: String? = null,
    val inlinedOccurrenceCount: Int? = null,
    val parameterName: String? = null,
    val parameterType: String? = null,
    val parameterPosition: Int? = null,
    val sourceKind: String? = null,
    val defaultCallSiteExpression: String? = null,
    val updatedCallSiteCount: Int? = null,
    val affectedFiles: List<String>? = null,
    val targetDescription: String? = null,
    val targetKind: String? = null,
    val nativeUsageCount: Int? = null,
    val newVisibility: String? = null,
    val memberName: String? = null,
    val memberKind: String? = null,
    val replaceUsages: Boolean? = null,
    val classParameterName: String? = null,
    val fieldParameterNames: List<String>? = null,
    val generateDelegate: Boolean? = null,
    val fieldNames: List<String>? = null,
    val getterNames: List<String>? = null,
    val setterNames: List<String>? = null,
    val fieldsVisibility: String? = null,
    val accessorsVisibility: String? = null,
    val encapsulateGet: Boolean? = null,
    val encapsulateSet: Boolean? = null,
    val useAccessorsWhenAccessible: Boolean? = null,
    val sourceClass: String? = null,
    val interfaceName: String? = null,
    val qualifiedInterfaceName: String? = null,
    val memberNames: List<String>? = null,
    val targetPackage: String? = null,
    val summary: String? = null,
    val code: McpRefactoringErrorCode? = null,
    val message: String? = null,
) {
    fun toJson(): String = JSON.encodeToString(this)

    companion object {
        private val JSON = Json { encodeDefaults = false }

        fun extractMethodSuccess(
            projectBasePath: String,
            filePath: String,
            methodName: String,
            summary: String,
        ) =
            McpRefactoringResult(
                ok = true,
                operation = "java_extract_method",
                filePath = filePath,
                projectBasePath = projectBasePath,
                methodName = methodName,
                summary = summary,
            )

        fun introduceVariableSuccess(
            projectBasePath: String,
            filePath: String,
            requestedVariableName: String,
            actualVariableName: String,
            variableType: String,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_introduce_variable",
            filePath = filePath,
            projectBasePath = projectBasePath,
            requestedVariableName = requestedVariableName,
            actualVariableName = actualVariableName,
            variableType = variableType,
            summary = summary,
        )

        fun introduceConstantSuccess(
            projectBasePath: String,
            filePath: String,
            requestedFieldName: String,
            actualFieldName: String,
            fieldType: String,
            targetClassQualifiedName: String,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_introduce_constant",
            filePath = filePath,
            projectBasePath = projectBasePath,
            requestedFieldName = requestedFieldName,
            actualFieldName = actualFieldName,
            fieldType = fieldType,
            fieldModifiers = listOf("private", "static", "final"),
            targetClassQualifiedName = targetClassQualifiedName,
            summary = summary,
        )

        fun introduceFieldSuccess(
            projectBasePath: String,
            filePath: String,
            requestedFieldName: String,
            actualFieldName: String,
            fieldType: String,
            targetClassQualifiedName: String,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_introduce_field",
            filePath = filePath,
            projectBasePath = projectBasePath,
            requestedFieldName = requestedFieldName,
            actualFieldName = actualFieldName,
            fieldType = fieldType,
            fieldModifiers = listOf("private", "final"),
            targetClassQualifiedName = targetClassQualifiedName,
            initializationPlace = "FIELD_DECLARATION",
            summary = summary,
        )

        fun inlineVariableSuccess(
            projectBasePath: String,
            filePath: String,
            variableName: String,
            inlinedOccurrenceCount: Int,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_inline_variable",
            projectBasePath = projectBasePath,
            filePath = filePath,
            variableName = variableName,
            inlinedOccurrenceCount = inlinedOccurrenceCount,
            summary = summary,
        )

        fun changeSignatureAddParameterSuccess(
            projectBasePath: String,
            filePath: String,
            methodName: String,
            parameterName: String,
            parameterType: String,
            parameterPosition: Int,
            defaultCallSiteExpression: String,
            updatedCallSiteCount: Int,
            affectedFiles: List<String>,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_change_signature_add_parameter",
            projectBasePath = projectBasePath,
            filePath = filePath,
            methodName = methodName,
            parameterName = parameterName,
            parameterType = parameterType,
            parameterPosition = parameterPosition,
            defaultCallSiteExpression = defaultCallSiteExpression,
            updatedCallSiteCount = updatedCallSiteCount,
            affectedFiles = affectedFiles,
            summary = summary,
        )

        fun introduceParameterSuccess(
            projectBasePath: String,
            filePath: String,
            methodName: String,
            parameterName: String,
            parameterType: String,
            parameterPosition: Int,
            sourceKind: String,
            updatedCallSiteCount: Int,
            affectedFiles: List<String>,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_introduce_parameter",
            projectBasePath = projectBasePath,
            filePath = filePath,
            methodName = methodName,
            parameterName = parameterName,
            parameterType = parameterType,
            parameterPosition = parameterPosition,
            sourceKind = sourceKind,
            updatedCallSiteCount = updatedCallSiteCount,
            affectedFiles = affectedFiles,
            summary = summary,
        )

        fun safeDeleteSuccess(
            projectBasePath: String,
            filePath: String,
            targetDescription: String,
            nativeUsageCount: Int,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_safe_delete",
            projectBasePath = projectBasePath,
            filePath = filePath,
            targetDescription = targetDescription,
            nativeUsageCount = nativeUsageCount,
            summary = summary,
        )

        fun moveInstanceMethodSuccess(
            projectBasePath: String,
            filePath: String,
            methodName: String,
            targetDescription: String,
            targetClassQualifiedName: String,
            newVisibility: String,
            updatedCallSiteCount: Int,
            affectedFiles: List<String>? = null,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_move_instance_method",
            filePath = filePath,
            projectBasePath = projectBasePath,
            methodName = methodName,
            targetDescription = targetDescription,
            targetClassQualifiedName = targetClassQualifiedName,
            newVisibility = newVisibility,
            updatedCallSiteCount = updatedCallSiteCount,
            affectedFiles = affectedFiles,
            summary = summary,
        )

        fun makeStaticSuccess(
            projectBasePath: String,
            filePath: String,
            memberName: String,
            memberKind: JavaMakeStaticMemberKind,
            replaceUsages: Boolean,
            classParameterName: String?,
            fieldParameterNames: List<String>,
            generateDelegate: Boolean,
            nativeUsageCount: Int,
            affectedFiles: List<String>? = null,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_make_static",
            filePath = filePath,
            projectBasePath = projectBasePath,
            memberName = memberName,
            memberKind = memberKind.name.lowercase(),
            replaceUsages = replaceUsages,
            classParameterName = classParameterName,
            fieldParameterNames = fieldParameterNames,
            generateDelegate = generateDelegate,
            nativeUsageCount = nativeUsageCount,
            affectedFiles = affectedFiles,
            summary = summary,
        )

        fun convertToInstanceMethodSuccess(
            projectBasePath: String,
            filePath: String,
            methodName: String,
            targetKind: String,
            targetDescription: String,
            targetClassQualifiedName: String,
            newVisibility: String?,
            nativeUsageCount: Int,
            affectedFiles: List<String>? = null,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_convert_to_instance_method",
            filePath = filePath,
            projectBasePath = projectBasePath,
            methodName = methodName,
            targetKind = targetKind,
            targetDescription = targetDescription,
            targetClassQualifiedName = targetClassQualifiedName,
            newVisibility = newVisibility,
            nativeUsageCount = nativeUsageCount,
            affectedFiles = affectedFiles,
            summary = summary,
        )

        fun encapsulateFieldsSuccess(
            projectBasePath: String,
            filePath: String,
            fieldNames: List<String>,
            getterNames: List<String>,
            setterNames: List<String>,
            fieldsVisibility: String?,
            accessorsVisibility: String,
            encapsulateGet: Boolean,
            encapsulateSet: Boolean,
            useAccessorsWhenAccessible: Boolean,
            nativeUsageCount: Int,
            affectedFiles: List<String>?,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_encapsulate_fields",
            filePath = filePath,
            projectBasePath = projectBasePath,
            fieldNames = fieldNames,
            getterNames = getterNames,
            setterNames = setterNames,
            fieldsVisibility = fieldsVisibility,
            accessorsVisibility = accessorsVisibility,
            encapsulateGet = encapsulateGet,
            encapsulateSet = encapsulateSet,
            useAccessorsWhenAccessible = useAccessorsWhenAccessible,
            nativeUsageCount = nativeUsageCount,
            affectedFiles = affectedFiles,
            summary = summary,
        )

        fun extractInterfaceSuccess(
            projectBasePath: String,
            filePath: String,
            sourceClass: String,
            interfaceName: String,
            qualifiedInterfaceName: String,
            memberNames: List<String>,
            targetPackage: String?,
            nativeUsageCount: Int,
            affectedFiles: List<String>?,
            summary: String,
        ) = McpRefactoringResult(
            ok = true,
            operation = "java_extract_interface",
            filePath = filePath,
            projectBasePath = projectBasePath,
            sourceClass = sourceClass,
            interfaceName = interfaceName,
            qualifiedInterfaceName = qualifiedInterfaceName,
            memberNames = memberNames,
            targetPackage = targetPackage,
            nativeUsageCount = nativeUsageCount,
            affectedFiles = affectedFiles,
            summary = summary,
        )

        fun failure(code: McpRefactoringErrorCode, message: String) =
            McpRefactoringResult(ok = false, code = code, message = message)
    }
}
